version: 2
project_name: cmvp

builds:
  - main: .
    binary: cmvp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: ethanolivertroy
    name: cmvp-tui

brews:
  - repository:
      owner: ethanolivertroy
      name: homebrew-sectools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ethanolivertroy/cmvp-tui"
    description: "Terminal UI for searching NIST CMVP validated cryptographic modules"
    license: "MIT"
    install: |
      bin.install "cmvp"
    test: |
      assert_match "CMVP", shell_output("#{bin}/cmvp --help 2>&1", 1)

scoops:
  - repository:
      owner: ethanolivertroy
      name: scoop-sectools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: bucket
    homepage: "https://github.com/ethanolivertroy/cmvp-tui"
    description: "Terminal UI for searching NIST CMVP validated cryptographic modules"
    license: "MIT"
