version: 2
project_name: cmvp

builds:
  - main: .
    binary: cmvp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: ethanolivertroy
    name: cmvp-tui

brews:
  - repository:
      owner: ethanolivertroy
      name: homebrew-sectools
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ethanolivertroy/cmvp-tui"
    description: "Terminal UI for searching NIST CMVP validated cryptographic modules"
    license: "MIT"
    install: |
      bin.install "cmvp"
    test: |
      assert_match "CMVP", shell_output("#{bin}/cmvp --help 2>&1", 1)
